export const Posts = [
    {
        id: 1,
        categ: 'GOOD TIMES',
        title: 'Mastering The Dance Floor: Learn How To Two-Step',
        excerpt: "If you've ever watched folks gliding across the honky-tonk dance floor and thought, I wish I could do that, you're in for a treat. In just a few moments, you'll not only discover the magic of the Two-Step, but you’ll also learn how to own it with confidence and how to dress the part for both",
        link: "#",
        publish: "September 6, 2022",
        author: "John Doe",
        alt: "featured",
        img: "/assets/images/post/1.jpg",
    },
    {
        id: 2,
        categ: 'FASHION',
        title: 'The path be beautiful, let us not ask where it leads',
        excerpt: "If you've ever watched folks gliding across the honky-tonk dance floor and thought, I wish I could do that, you're in for a treat. In just a few moments, you'll not only discover the magic of the Two-Step, but you’ll also learn how to own it with confidence and how to dress the part for both",
        link: "#",
        publish: "September 6, 2022",
        author: "John Doe",
        alt: "featured1",
        img: "/assets/images/post/2.jpg",
    },
    {
        id: 3,
        categ: 'LIFESTYLE',
        title: 'Leisure is the Mother of Philosophy.',
        excerpt: "If you've ever watched folks gliding across the honky-tonk dance floor and thought, I wish I could do that, you're in for a treat. In just a few moments, you'll not only discover the magic of the Two-Step, but you’ll also learn how to own it with confidence and how to dress the part for both",
        link: "#",
        publish: "September 6, 2022",
        author: "John Doe",
        alt: "featured2",
        img: "/assets/images/post/3.jpg",
    },
    {
        id: 4,
        categ: 'Style Guide',
        title: 'Leisure is the Mother of Philosophy.',
        excerpt: "If you've ever watched folks gliding across the honky-tonk dance floor and thought, I wish I could do that, you're in for a treat. In just a few moments, you'll not only discover the magic of the Two-Step, but you’ll also learn how to own it with confidence and how to dress the part for both",
        link: "#",
        publish: "September 6, 2022",
        author: "John Doe",
        alt: "featured2",
        img: "/assets/images/post/4.jpg",
    },
    {
        id: 5,
        categ: 'Kindred Spirits',
        title: 'Leisure is the Mother of Philosophy.',
        excerpt: "If you've ever watched folks gliding across the honky-tonk dance floor and thought, I wish I could do that, you're in for a treat. In just a few moments, you'll not only discover the magic of the Two-Step, but you’ll also learn how to own it with confidence and how to dress the part for both",
        link: "#",
        publish: "September 6, 2022",
        author: "John Doe",
        alt: "featured2",
        img: "/assets/images/post/5.jpg",
    },
    {
        id: 6,
        categ: 'Kindred Spirits',
        title: 'Leisure is the Mother of Philosophy.',
        excerpt: "If you've ever watched folks gliding across the honky-tonk dance floor and thought, I wish I could do that, you're in for a treat. In just a few moments, you'll not only discover the magic of the Two-Step, but you’ll also learn how to own it with confidence and how to dress the part for both",
        link: "#",
        publish: "September 6, 2022",
        author: "John Doe",
        alt: "featured2",
        img: "/assets/images/post/6.jpg",
    },
]